# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1psXdn54HF9o5spYALlugPVTsCZoH5dv3
"""

# Datasets standard (tous inclus dans scikit-learn)
from sklearn import datasets

iris       = datasets.load_iris()           # 150 x 4, 3 classes
breast     = datasets.load_breast_cancer()  # 569 x 30, binaire
wine       = datasets.load_wine()           # 178 x 13, 3 classes
digits     = datasets.load_digits()         # 1797 x 64, 10 classes
diabetes   = datasets.load_diabetes()       # 442 x 10, regression
california = datasets.fetch_california_housing()  # 20640 x 8, prix

# Assign X and y from a dataset (e.g., Iris) for the split
X, y = iris.data, iris.target

# Split stratifié 80/20
from sklearn.model_selection import train_test_split
X_tr, X_te, y_tr, y_te = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y  # stratify pour classification
)

# Scale data for models that require it
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_tr_s = scaler.fit_transform(X_tr)
X_te_s = scaler.transform(X_te)

# Pipeline : evite le data leakage (scaler ajuste uniquement sur train)
from sklearn.pipeline import Pipeline
# Define a dummy model for the pipeline example if MonModele is not defined
from sklearn.linear_model import LogisticRegression as MonModele
model = Pipeline([("sc", StandardScaler()), ("clf", MonModele())])

from sklearn.datasets import fetch_20newsgroups

# Charger un sous-ensemble du dataset 20 Newsgroups pour l'entraînement
newsgroups_train = fetch_20newsgroups(subset='all', remove=('headers', 'footers', 'quotes'))
train_texts = newsgroups_train.data
train_labels = newsgroups_train.target

print(f"Nombre d'échantillons d'entraînement : {len(train_texts)}")
print(f"Nombre de classes : {len(newsgroups_train.target_names)}")
print("Jeu de données textuelles chargé avec succès.")

from sklearn.linear_model import LogisticRegression
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

lr = Pipeline([
    ("sc", StandardScaler()),
    ("lr", LogisticRegression(
        max_iter=1000,   # augmenter si ConvergenceWarning
        C=1.0,           # inverse regularisation (grand = moins regularise)
        random_state=42
    ))
])
lr.fit(X_tr, y_tr)
pred  = lr.predict(X_te)
proba = lr.predict_proba(X_te)   # probabilites par classe

# Coefficients : importance des features
coefs = lr["lr"].coef_  # (n_classes, n_features)

from sklearn.tree import DecisionTreeClassifier, plot_tree

dt = DecisionTreeClassifier(
    max_depth=4,         # evite l'overfitting
    min_samples_split=5, # noeud non divise si < 5 points
    random_state=42
)
dt.fit(X_wine_tr, y_wine_tr)
importances = dt.feature_importances_  # importance de chaque feature (Gini)

# Visualisation de l'arbre
fig, ax = plt.subplots(figsize=(20, 8))
plot_tree(dt, feature_names=wine.feature_names,
          class_names=wine.target_names, filled=True, ax=ax)

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import learning_curve
import numpy as np
import matplotlib.pyplot as plt

rf = RandomForestClassifier(
    n_estimators=100,      # plus = meilleur, mais plus lent
    max_features="sqrt",   # √p features par noeud
    random_state=42, n_jobs=-1
)
rf.fit(X_tr, y_tr)

# Feature importances (reduction de Gini moyenne sur tous les arbres)
importances = rf.feature_importances_

# Diagnostiquer l'overfitting
train_sz, train_sc, test_sc = learning_curve(rf, X_tr, y_tr, cv=5, n_jobs=-1)

plt.figure(figsize=(10, 6))
plt.plot(train_sz, train_sc.mean(axis=1), label="Training Score")
plt.plot(train_sz, test_sc.mean(axis=1), label="Cross-validation Score")
plt.xlabel("Training Set Size")
plt.ylabel("Accuracy")
plt.title("Random Forest Learning Curve")
plt.legend()
plt.grid(True)
plt.show()

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score

gb = GradientBoostingClassifier(
    n_estimators=200,   # nb d'arbres sequentiels
    learning_rate=0.1,  # eta : petit -> meilleure generalisation
    max_depth=3,        # arbres peu profonds
    subsample=0.8,      # stochastic GBM
    random_state=42
)
gb.fit(X_tr, y_tr)
proba = gb.predict_proba(X_te)[:, 1]  # probabilite classe positive

# Convergence : accuracy par iteration
staged = [accuracy_score(y_te, p) for p in gb.staged_predict(X_te)]

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.plot(staged)
plt.xlabel("Nombre d'estimateurs")
plt.ylabel("Accuracy")
plt.title("Courbe de convergence du Gradient Boosting")
plt.grid(True)
plt.show()

import pandas as pd

feature_importances = pd.Series(gb.feature_importances_, index=iris.feature_names).sort_values(ascending=False)
print("Importances des caractéristiques pour Gradient Boosting:")
print(feature_importances)

from sklearn.svm import SVC

svm = Pipeline([
    ("sc",  StandardScaler()),  # OBLIGATOIRE
    ("svm", SVC(
        kernel="rbf",      # gaussien : polyvalent
        C=1.0,             # penalite d'erreur
        gamma="scale",     # adaptatif : 1/(p * Var(X))
        probability=True   # pour predict_proba (plus lent)
    ))
])

from sklearn.neighbors import KNeighborsClassifier

# Trouver le k optimal
for k in range(1, 21):
    knn = Pipeline([("sc", StandardScaler()),
                    ("knn", KNeighborsClassifier(n_neighbors=k))])
    knn.fit(X_tr, y_tr)
    acc = accuracy_score(y_te, knn.predict(X_te))

from sklearn.naive_bayes import GaussianNB

gnb = GaussianNB()    # pas de normalisation necessaire
gnb.fit(X_tr, y_tr)
proba = gnb.predict_proba(X_te)   # probabilites posterieures calibrees

print(gnb.theta_)  # (n_classes, n_features) : moyennes par classe
print(gnb.var_)    # (n_classes, n_features) : variances par classe

from sklearn.ensemble import AdaBoostClassifier
from sklearn.metrics import accuracy_score

ada = AdaBoostClassifier(
    n_estimators=100, learning_rate=0.5,
    algorithm="SAMME", random_state=42
)
ada.fit(X_tr, y_tr)

# Evolution de l'accuracy par iteration
staged_acc = [accuracy_score(y_te, p) for p in ada.staged_predict(X_te)]

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.plot(staged_acc)
plt.xlabel("Nombre d'estimateurs")
plt.ylabel("Accuracy")
plt.title("Courbe d'évolution de l'Accuracy pour AdaBoost")
plt.grid(True)
plt.show()

from sklearn.neural_network import MLPClassifier
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

mlp = Pipeline([
    ("sc",  StandardScaler()),  # OBLIGATOIRE
    ("mlp", MLPClassifier(
        hidden_layer_sizes=(256, 128, 64),  # 3 couches cached
        activation="relu",
        solver="adam",
        max_iter=300,
        early_stopping=True,  # arret si val ne s'ameliore plus
        validation_fraction=0.1,
        random_state=42
    ))
])

# Fit the model to make loss_curve_ available
mlp.fit(X_tr_s, y_tr)

loss_curve = mlp["mlp"].loss_curve_   # perte par iteration

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.plot(loss_curve)
plt.xlabel("Nombre d'itérations")
plt.ylabel("Perte")
plt.title("Courbe de perte du MLPClassifier")
plt.grid(True)
plt.show()

from sklearn.ensemble import ExtraTreesClassifier
from sklearn.model_selection import train_test_split
from sklearn import datasets

# Load the wine dataset and split it
wine = datasets.load_wine()
X_wine, y_wine = wine.data, wine.target
X_wine_tr, X_wine_te, y_wine_tr, y_wine_te = train_test_split(
    X_wine, y_wine, test_size=0.2, random_state=42, stratify=y_wine
)

et = ExtraTreesClassifier(n_estimators=200, random_state=42, n_jobs=-1)
et.fit(X_wine_tr, y_wine_tr)
importances = et.feature_importances_

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis

lda = LinearDiscriminantAnalysis()
lda.fit(X_tr, y_tr)

# Reduction de dimension (ex: Iris 4D -> 2D)
X_2d = lda.transform(X)   # projection sur les axes discriminants

import pandas as pd
import matplotlib.pyplot as plt

feature_importances_et = pd.Series(importances, index=wine.feature_names).sort_values(ascending=False)

plt.figure(figsize=(12, 8))
feature_importances_et.plot(kind='barh')
plt.title("Importance des caractéristiques pour ExtraTreesClassifier (Wine dataset)")
plt.xlabel("Importance")
plt.ylabel("Caractéristique")
plt.tight_layout()
plt.show()

print("Importances des caractéristiques pour ExtraTreesClassifier:")
print(feature_importances_et)

from sklearn.discriminant_analysis import LinearDiscriminantAnalysis
import matplotlib.pyplot as plt
import seaborn as sns

# Apply LDA to the wine dataset
lda_wine = LinearDiscriminantAnalysis(n_components=2)
X_wine_2d = lda_wine.fit_transform(X_wine, y_wine)

# Create a DataFrame for easier plotting
import pandas as pd
df_wine_2d = pd.DataFrame(data=X_wine_2d, columns=['LDA Component 1', 'LDA Component 2'])
df_wine_2d['target'] = y_wine
df_wine_2d['target_names'] = wine.target_names[y_wine]

plt.figure(figsize=(10, 8))
sns.scatterplot(
    x='LDA Component 1',
    y='LDA Component 2',
    hue='target_names',
    data=df_wine_2d,
    palette='viridis',
    s=100,
    alpha=0.8
)
plt.title('LDA of Wine Dataset by Class')
plt.xlabel('LDA Component 1')
plt.ylabel('LDA Component 2')
plt.grid(True)
plt.legend(title='Wine Class')
plt.tight_layout()
plt.show()

display(df_wine_2d.head())

"""### Informations générales du DataFrame `df_wine_2d`"""

df_wine_2d.info()

"""### Statistiques descriptives du DataFrame `df_wine_2d`"""

display(df_wine_2d.describe())

display(df_wine_2d.describe())

"""### Répartition des classes cibles dans `df_wine_2d`"""

print('Répartition de la classe réelle (target):')
display(df_wine_2d['target_names'].value_counts())

print('\nRépartition des prédictions QDA (QDA_prediction_names):')
display(df_wine_2d['QDA_prediction_names'].value_counts())

"""### Vérification des points mal classifiés"""

print('\nNombre de points mal classifiés par QDA:')
display(df_wine_2d['is_misclassified'].value_counts())

print('\nPoints mal classifiés par QDA:')
display(df_wine_2d[df_wine_2d['is_misclassified'] == True].head())

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(10, 8))
sns.scatterplot(
    x='LDA Component 1',
    y='LDA Component 2',
    hue='target_names',
    data=df_wine_2d,
    palette='viridis',
    s=100,
    alpha=0.8
)
plt.title('LDA des Composantes du Dataset Wine par Classe Réelle')
plt.xlabel('LDA Component 1')
plt.ylabel('LDA Component 2')
plt.grid(True)
plt.legend(title='Classe du Vin')
plt.tight_layout()
plt.show()

from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
qda = QuadraticDiscriminantAnalysis(reg_param=0.1, store_covariance=True)  # reg: evite singularite

from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis

qda = QuadraticDiscriminantAnalysis(reg_param=0.1, store_covariance=True)
qda.fit(X_tr, y_tr)

print("Class prior probabilities (priors_):")
print(qda.priors_)

print("\nClass means (means_):")
print(qda.means_)

# The covariances_ attribute is currently not being set, even with store_covariance=True.
# Removing the line that attempts to access it to avoid an AttributeError.
# print("\nClass covariance matrices (covariances_):")
# print(qda.covariances_)

from sklearn.discriminant_analysis import QuadraticDiscriminantAnalysis
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

# Ensure X_wine and y_wine are loaded (they should be from cell HATQ1_CcYXPp)
# If not, add:
# wine = datasets.load_wine()
# X_wine, y_wine = wine.data, wine.target

# Initialize and fit QDA for the wine dataset
qda_wine = QuadraticDiscriminantAnalysis(reg_param=0.1, store_covariance=True) # store_covariance for potential debugging
qda_wine.fit(X_wine, y_wine)

# Get predictions from the QDA model on the original wine data
qda_predictions = qda_wine.predict(X_wine)

# Add QDA predictions to the existing df_wine_2d for plotting
df_wine_2d['QDA_predictions'] = qda_predictions
df_wine_2d['QDA_prediction_names'] = wine.target_names[qda_predictions]

# Identify misclassified points
df_wine_2d['is_misclassified'] = (df_wine_2d['target'] != df_wine_2d['QDA_predictions'])

plt.figure(figsize=(12, 9))

# Plot correctly classified points
sns.scatterplot(
    x='LDA Component 1',
    y='LDA Component 2',
    hue='QDA_prediction_names',
    style='is_misclassified',
    markers={False: 'o', True: 'X'},
    s=100, alpha=0.8,
    data=df_wine_2d[~df_wine_2d['is_misclassified']],
    palette='viridis'
)

# Plot misclassified points separately with a different marker
sns.scatterplot(
    x='LDA Component 1',
    y='LDA Component 2',
    hue='QDA_prediction_names',
    style='is_misclassified',
    markers={False: 'o', True: 'X'},
    s=150, alpha=1.0,
    data=df_wine_2d[df_wine_2d['is_misclassified']],
    palette='viridis',
    legend=False,
    marker='X'
)

plt.title('QDA Predictions on Wine Dataset in LDA 2D Space')
plt.xlabel('LDA Component 1')
plt.ylabel('LDA Component 2')
plt.grid(True)
plt.legend(title='QDA Prediction')
plt.tight_layout()
plt.show()

from sklearn.linear_model import SGDClassifier

sgd = Pipeline([
    ("sc",  StandardScaler()),
    ("sgd", SGDClassifier(loss="log_loss", penalty="l2",
                           max_iter=1000, random_state=42))
])
# Apprentissage en ligne (incremental) :
# sgd["sgd"].partial_fit(X_new, y_new, classes=np.unique(y))

from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier

bag = BaggingClassifier(
    estimator=DecisionTreeClassifier(),
    n_estimators=100, max_samples=0.8,
    bootstrap=True, oob_score=True,
    random_state=42, n_jobs=-1
)
# The oob_score_ attribute is only available after fitting the model
bag.fit(X_tr, y_tr) # Assuming X_tr and y_tr are defined
print(f"OOB Score : {bag.oob_score_:.4f}")

from sklearn.ensemble import VotingClassifier

vote = VotingClassifier(
    estimators=[("lr", lr), ("rf", rf), ("svm", svm)],
    voting="soft"   # moyenne des probas (meilleur que hard en general)
)

from sklearn.ensemble import StackingClassifier
from sklearn.linear_model import LogisticRegression

stack = StackingClassifier(
    estimators=[("rf", rf), ("gb", gb), ("knn", knn)],
    final_estimator=LogisticRegression(max_iter=1000),
    cv=5,
    stack_method="predict_proba"
)

from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import RBF

gpc = GaussianProcessClassifier(kernel=RBF(), random_state=42)
gpc.fit(X_tr_s, y_tr)
proba = gpc.predict_proba(X_te_s)  # probabilites bien calibrees
print(gpc.kernel_)                  # hyperparametres optimises

from sklearn.linear_model import RidgeClassifier, RidgeClassifierCV

rc  = RidgeClassifier(alpha=1.0)            # solution analytique, rapide
rcv = RidgeClassifierCV(alphas=[0.01, 0.1, 1.0, 10.0])  # auto-selection alpha

from sklearn.naive_bayes import MultinomialNB
from sklearn.feature_extraction.text import TfidfVectorizer

pipe = Pipeline([
    ("tfidf", TfidfVectorizer(max_features=10000, ngram_range=(1,2))),
    ("mnb",   MultinomialNB(alpha=0.1))   # lissage de Laplace
])
pipe.fit(train_texts, train_labels)

print("Hyperparamètres du modèle MultinomialNB :")
print(pipe['mnb'].get_params())

from sklearn.datasets import fetch_20newsgroups
from sklearn.metrics import accuracy_score

# Charger un sous-ensemble du dataset 20 Newsgroups pour les tests
newsgroups_test = fetch_20newsgroups(subset='test', remove=('headers', 'footers', 'quotes'))
test_texts = newsgroups_test.data
test_labels = newsgroups_test.target

print(f"Nombre d'échantillons de test : {len(test_texts)}")
print(f"Nombre de classes : {len(newsgroups_test.target_names)}")
print("Jeu de données textuelles de test chargé avec succès.")

# Faire des prédictions sur les données de test
predictions = pipe.predict(test_texts)

# Calculer l'accuracy
accuracy = accuracy_score(test_labels, predictions)

print(f"Accuracy du modèle MultinomialNB sur les données de test : {accuracy:.4f}")

from sklearn.naive_bayes import BernoulliNB
from sklearn.preprocessing import Binarizer

bnb = Pipeline([
    ("bin", Binarizer(threshold=0.0)),  # binarise les features
    ("bnb", BernoulliNB(alpha=1.0))
])

from sklearn.linear_model import Perceptron, PassiveAggressiveClassifier

# Perceptron : mise a jour uniquement sur les erreurs
perc = Pipeline([("sc", StandardScaler()),
                 ("p",  Perceptron(max_iter=1000, eta0=0.1, random_state=42))])

# Passive-Aggressive : correction minimale sur les erreurs
pa = Pipeline([("sc", StandardScaler()),
               ("pa", PassiveAggressiveClassifier(C=1.0, max_iter=1000))])

from sklearn.calibration import CalibratedClassifierCV, calibration_curve
from sklearn.metrics import brier_score_loss
from sklearn.svm import SVC
import numpy as np

# Calibrer un SVM (pas de probas par defaut)
cal_svm = CalibratedClassifierCV(SVC(kernel="rbf", probability=True), cv=5, method="sigmoid")
cal_svm.fit(X_tr_s, y_tr)
proba = cal_svm.predict_proba(X_te_s)

# Binariser y_te pour la calibration_curve (par exemple, classe 1 vs toutes les autres)
y_te_binary_class1 = (y_te == 1).astype(int)

# Correction: Utilisez y_te_binary_class1 et les probabilités de la classe positive
frac_pos, mean_pred = calibration_curve(y_te_binary_class1, proba[:,1], n_bins=10, pos_label=1)
brier = brier_score_loss(y_te_binary_class1, proba[:,1])  # 0=parfait

print(f"Brier Score: {brier:.4f}")

from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_squared_error
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline

lr = Pipeline([("sc", StandardScaler()), ("lr", LinearRegression())])
lr.fit(X_tr, y_tr)
pred = lr.predict(X_te)

residuals = y_te - pred  # residus : doivent etre aleatoires autour de 0
r2   = r2_score(y_te, pred)
rmse = np.sqrt(mean_squared_error(y_te, pred))

from sklearn.linear_model import Ridge, Lasso, ElasticNet

Ridge(alpha=1.0)                     # L2 : reduit tous les coefs
Lasso(alpha=0.1, max_iter=5000)      # L1 : annule les coefs non pertinents
ElasticNet(alpha=0.1, l1_ratio=0.5)  # L1 + L2

# Chemin de regularisation Lasso
alphas = np.logspace(-3, 2, 50)
coef_paths = [Lasso(alpha=a).fit(X_tr_s, y_tr).coef_ for a in alphas]

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor

dtr = DecisionTreeRegressor(max_depth=6, random_state=42)
rfr = RandomForestRegressor(n_estimators=100, n_jobs=-1, random_state=42)

rfr.fit(X_tr, y_tr)
pred_rfr = rfr.predict(X_te)

r2_rfr = r2_score(y_te, pred_rfr)
print(f"R2 score pour RandomForestRegressor: {r2_rfr:.4f}")

from sklearn.ensemble import GradientBoostingRegressor
from sklearn.metrics import r2_score

gbr = GradientBoostingRegressor(
    n_estimators=300, learning_rate=0.1,
    max_depth=4, subsample=0.8, random_state=42
)
gbr.fit(X_tr, y_tr)
staged_r2 = [r2_score(y_te, p) for p in gbr.staged_predict(X_te)]

import matplotlib.pyplot as plt

plt.figure(figsize=(10, 6))
plt.plot(staged_r2)
plt.xlabel("Nombre d'estimateurs")
plt.ylabel("Score R2")
plt.title("Courbe d'évolution du score R2 pour Gradient Boosting Regressor")
plt.grid(True)
plt.show()

from sklearn.svm import SVR

svr = Pipeline([("sc", StandardScaler()),
                ("svr", SVR(kernel="rbf", C=100, epsilon=0.1))])

from sklearn.neighbors import KNeighborsRegressor

knnr = Pipeline([("sc", StandardScaler()),
                 ("knn", KNeighborsRegressor(n_neighbors=7, weights="distance"))])

from sklearn.neural_network import MLPRegressor
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import StandardScaler

mlp_reg = Pipeline([
    ("sc",  StandardScaler()),
    ("mlp", MLPRegressor(
        hidden_layer_sizes=(128, 64, 32),  # 3 couches cachees
        activation="relu",
        solver="adam",
        max_iter=500,
        early_stopping=True,  # arret si val ne s'ameliore plus
        validation_fraction=0.1,
        random_state=42
    ))
])

# Fit the model to make loss_curve_ available
mlp_reg.fit(X_tr_s, y_tr)

loss_curve = mlp_reg["mlp"].loss_curve_   # perte par iteration
val_scores  = mlp_reg["mlp"].validation_scores_ # score de validation par iteration

import matplotlib.pyplot as plt

plt.figure(figsize=(12, 6))
plt.plot(loss_curve, label='Training Loss')
plt.plot(val_scores, label='Validation Score')
plt.xlabel("Nombre d'itérations")
plt.ylabel("Perte / Score")
plt.title("Courbe de perte et de validation du MLPRegressor")
plt.legend()
plt.grid(True)
plt.show()

from sklearn.linear_model import BayesianRidge

br = BayesianRidge(max_iter=500)
br.fit(X_tr_s, y_tr)
# retourne l'incertitude sur chaque prediction
pred, std = br.predict(X_te_s, return_std=True)
# IC 95% : [pred - 2*std, pred + 2*std]

"""### Résultats du modèle BayesianRidge"""

print("Prédictions de BayesianRidge :\n", pred)
print("Écart-type des prédictions de BayesianRidge :\n", std)

from sklearn.linear_model import HuberRegressor

huber = HuberRegressor(epsilon=1.35)  # robuste aux outliers
# epsilon=1.35 : 95% d'efficacite vs OLS sur donnees normales

from sklearn.linear_model import ARDRegression
from sklearn.cross_decomposition import PLSRegression

ard = ARDRegression()   # hyperparametre distinct par feature -> sparse
pls = PLSRegression(n_components=4)  # maximise cov(X, y)
pls.fit(X_tr_s, y_tr)          # Entraîner le modèle avant de prédire
pls.predict(X_te_s).ravel()          # attention : shape (n, 1) -> ravel()

from sklearn.linear_model import SGDRegressor
from sklearn.ensemble import BaggingRegressor, StackingRegressor
from sklearn.linear_model import Ridge
from sklearn.tree import DecisionTreeRegressor

sgd_r = SGDRegressor(loss="squared_error", penalty="l2", alpha=0.001)
bag_r = BaggingRegressor(estimator=DecisionTreeRegressor(max_depth=6),
                          n_estimators=100, oob_score=True, n_jobs=-1)
stk_r = StackingRegressor(
    estimators=[("rf", rfr), ("gb", gbr)],
    final_estimator=Ridge(alpha=1.0), cv=5
)

from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import RBF, ConstantKernel as C, WhiteKernel

kernel = C(1.0) * RBF(1.0) + WhiteKernel(1.0)
gpr = GaussianProcessRegressor(kernel=kernel, n_restarts_optimizer=3)
gpr.fit(X_tr_s, y_tr)
pred, std = gpr.predict(X_te_s, return_std=True)  # IC quantifie

"""### Résultats du modèle GaussianProcessRegressor"""

print("Prédictions de GaussianProcessRegressor :\n", pred)
print("Écart-type des prédictions de GaussianProcessRegressor :\n", std)

from sklearn.preprocessing import PolynomialFeatures

poly = Pipeline([
    ("poly",  PolynomialFeatures(degree=2, include_bias=False)),
    ("sc",    StandardScaler()),
    ("ridge", Ridge(alpha=1.0))   # regularisation obligatoire deg > 1
])
# deg=2, p=10 -> 65 features ; deg=3, p=10 -> 285 features

from sklearn.linear_model import QuantileRegressor

# Estimation du quantile tau de y|x (pas la moyenne)
qr = QuantileRegressor(quantile=0.5, alpha=0.001, solver="highs")
# Intervalles de prediction asymetriques : [Q10, Q90] ~ 80% coverage

from sklearn.isotonic import IsotonicRegression
from sklearn.linear_model import RANSACRegressor, TheilSenRegressor

iso    = IsotonicRegression(out_of_bounds="clip")   # monotone croissante
ransac = RANSACRegressor(residual_threshold=50, random_state=42)
ts     = TheilSenRegressor(max_subpopulation=1000, random_state=42)

from sklearn.linear_model import TweedieRegressor
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Re-define X_tr_s and y_tr for this cell if it's run independently
iris = datasets.load_iris()
X, y = iris.data, iris.target
X_tr, X_te, y_tr, y_te = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)
scaler = StandardScaler()
X_tr_s = scaler.fit_transform(X_tr)

# power=0: Gaussienne, 1: Poisson, 2: Gamma (toujours y > 0)
tw = TweedieRegressor(power=1, alpha=0.5, link="log", max_iter=1000)
tw.fit(X_tr_s, np.clip(y_tr, 0.01, None))

from sklearn.model_selection import GridSearchCV, StratifiedKFold
from sklearn.ensemble import RandomForestClassifier

param_grid = {"n_estimators": [50, 100, 200],
              "max_depth": [None, 5, 10],
              "max_features": ["sqrt", "log2"]}

gs = GridSearchCV(
    estimator=RandomForestClassifier(random_state=42),
    param_grid=param_grid,
    cv=StratifiedKFold(5, shuffle=True, random_state=42),
    scoring="accuracy", n_jobs=-1
)
gs.fit(X_tr, y_tr)
print(gs.best_params_, gs.best_score_)
best_model = gs.best_estimator_

from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint, uniform

param_dist = {
    "n_estimators"  : randint(50, 500),
    "learning_rate" : uniform(0.01, 0.3),
    "max_depth"     : randint(2, 8),
}
rs = RandomizedSearchCV(
    gbr, param_distributions=param_dist,
    n_iter=50, cv=5, scoring="r2", n_jobs=-1, random_state=42
)

from sklearn.model_selection import (StratifiedKFold, RepeatedStratifiedKFold,
                                      cross_validate)

cv_results = cross_validate(
    model, X, y,
    cv=RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=42),
    scoring=["accuracy", "f1_macro"],
    return_train_score=True   # diagnostiquer train vs val
)

display(cv_results)

import pandas as pd
df_cv_results = pd.DataFrame(cv_results)
display(df_cv_results)

import matplotlib.pyplot as plt
import seaborn as sns

plt.figure(figsize=(12, 6))

# Histogramme des scores de précision de test
plt.subplot(1, 2, 1)
sns.histplot(df_cv_results['test_accuracy'], bins=5, kde=True)
plt.title('Distribution de la précision de test (test_accuracy)')
plt.xlabel('Précision (Accuracy)')
plt.ylabel('Fréquence')
plt.grid(True, linestyle='--', alpha=0.7)

# Box plot des scores de précision de test
plt.subplot(1, 2, 2)
sns.boxplot(y=df_cv_results['test_accuracy'])
plt.title('Box Plot de la précision de test (test_accuracy)')
plt.ylabel('Précision (Accuracy)')
plt.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()